# Post-Cinema (Winter 2019)

## FILMSTUD 215/415: Post-Cinema

**Seminar:** Prof. Shane Denson  
**Time:** Tue 4:30-7:20pm  
**Room:** McMurtry 370  
**Office:** McMurtry 318  
**Office Hours:** TBD  
**Email:** shane.denson@stanford.edu

**Screenings:**  
Thurs 6:30-9:20pm  
Room: McMurtry 350

## Course Description

In this seminar, we will try to come to terms with twenty-first century motion pictures by thinking through a variety of concepts and theoretical approaches designed to explain their relations and differences from the cinema of the previous century. We will consider the impact of digital technologies on film, think about the cultural contexts and aesthetic practices of contemporary motion pictures, and try to understand the experiential dimensions of spectatorship in today's altered viewing conditions.

In addition to viewing a wide range of recent and contemporary films, we will also engage more directly and materially with post-cinematic moving images: we will experiment with scholarly and experimental uses of nonlinear video editing for the purposes of film analysis, cinemetrics, and a variety of academic and creative responses to post-cinematic media.

The course addresses key issues in recent film and media theory and, especially in its hands-on components, encourages experimentation with methods of digital humanities, computational media art, and other creative practices.

## Course Themes and Objectives

In this course, we set out from the apparent "chaos" that contemporary cinema often presents to us: the seemingly incoherent and unmotivated camerawork and editing, for example, by which many action films of the twenty-first century mark their departure from the "classical" norms of Hollywood-style narration and formal construction. From here, we seek to make sense more generally of cinema's transformation in terms of new technologies and techniques (e.g. digital imaging processes, nonlinear editing, and attendant editing styles), in terms of new modes of cinematic distribution and reception (e.g. DVD, Blu-Ray, and streaming services, HD TVs, smartphones, and tablet computers, but also IMAX 3-D and similar transformations of the big screen), in terms of non-classical narrative styles (e.g. recursive, database-like, non-linear, and even non-sequitur forms of storytelling), and in terms of broader phenomenological and environmental shifts that inform our experience, our embodiment, and our subjectivity in the digital era.

Several key concepts will help to orient our thinking about twenty-first century cinema and its relation to earlier cinematic modes. The first is "chaos cinema," a term which Matthias Stork popularized in a compelling set of video essays focused particularly on recent action cinema; beyond this context, however, Stork's notion of "chaos" resonates with the feelings and fears of many critics and theorists in the face of digital-era cinema. This broader perception of chaos is sometimes traced back to the digital unmooring of images from the indexical referents to which photographic films remained tied; on this basis, the somewhat oxymoronic term "digital film" is often linked to an even more unsettling, because more basic, sense of chaos: according to some critics, the digital (and the moving images it produces and supports) is correlated with a sweeping transformation of human society and subjectivity itself. On the other hand, though, not all critics are similarly alarmed by digital-era chaos. David Bordwell's concept of "intensified continuity" effectively denies the radical stylistic break announced in Stork's analysis; Bordwell sees the newer films as perhaps faster and even more hectic than classical Hollywood fare, but basically constructed according to principles of classical continuity – just intensified. By way of contrast, Steven Shaviro's notion of "post-continuity" – developed in the context of his analysis of "post-cinematic affect" – provides another view of contemporary moving image culture, one which links formal and aesthetic transformations not only with new technologies but also with broader social, cultural, and economic changes underway right now.

As we think through these and related concepts, we will engage a variety of recent movies from formal, phenomenological, affective, cultural, and environmental perspectives. We will seek to understand whether a radical change has taken place in recent cinema, to assess what its significance might be, and in this way begin to think through the implications of and for our viewing habits in the twenty-first century. Crucial to these explorations will be a hands-on engagement with post-cinematic moving images: we will dissect, analyze, compile, synthesize, juxtapose, quantify, and deform digital images in an attempt to understand and respond to post-cinema through new and emerging scholarly and creative practices.

**Please make sure you are registered for the class on Canvas. Handouts and additional course material will be posted there.**

## Required Textbook

Denson, Shane, and Julia Leyda, eds. *Post-Cinema: Theorizing 21st-Century Film*. Sussex: REFRAME Books, 2016.  
[Open-access book freely available in HTML and PDF versions: http://reframe.sussex.ac.uk/post-cinema/]

Additional readings (listed in the course schedule) will be made available via Canvas.

## Course Requirements

1. Regular attendance and preparation for class. Irregular attendance will negatively affect your final grade. Active participation will help improve your final grade. Readings are to be completed by the date listed on the syllabus.

2. Short written and/or videographic responses to the reading and viewing assignments each week. Questions or prompts will be announced in class the week prior. Please be prepared to present your text or video response in class. You are allowed no more than one missing assignment; late assignments (i.e. assignments received after class and up to 7 days afterwards) will count as half-complete (i.e., you are allowed no more than two late assignments). Assignments received more than 7 days late will not be accepted.

3. Presentation (20-30 minutes) of readings and relevant materials, followed by moderation of discussion. Your presentation should summarize readings, highlight particularly interesting or controversial aspects, and connect them to other relevant materials (texts, films, videos, artworks, etc.) and contexts, as well as formulating questions that will help focus class discussion. Your task is essentially to frame and guide our discussion of the readings, and to insert them into our larger ongoing discussion.

4. Final assignment (details below).

## Grading

Your final grade for the course will be calculated as follows:
- 30% Weekly assignments
- 20% In-Class Presentation/Discussion
- 50% Final project

## Final Assignment

There are two basic options for your final assignment: 1) a traditional term paper, or 2) a piece of scholarly videographic work (or related critical media project). Details for each type of assignment are listed below:

### Option #1 – Term Paper

Term papers (5000 words) are to be submitted by **Friday, March 22, 2019 (no later than 6:30pm)**. As a prerequisite for the final paper, a 1-2 page proposal will be due in class on **February 26, 2019**; you should be prepared to discuss your progress and turn in an updated proposal or progress report on the final day of class **(March 12, 2019)**. In your proposal, you should outline the focus or object of your analysis, explain the specific method(s) of analysis, state your reasons for choosing this approach to the topic, and formulate a tentative thesis statement. The final paper should be written in a scholarly format, with a complete bibliography, and should consist of the following:

1. **A brief introduction** outlining your topic and stating – as clearly and precisely as possible – the thesis of your paper. This section should usually be no more than one paragraph long.

2. **A short description** of the film(s) or other object(s) of your analysis. Here you should provide any essential background that might be needed for the reader to understand your analysis. You should assume an educated reader, who is familiar with film and media studies but perhaps has not seen the films (or other media) being discussed in your paper. If it is not relevant to your argument, do not engage in lengthy plot summaries. On the other hand, make sure that the reader has enough context (narrative or otherwise) to understand the more detailed analysis that follows. Overall, in this section you must find the right balance, which you can do by considering whether each detail is truly relevant and informative with respect to your argument. Anthropologist and cybernetician Gregory Bateson defined information as "a difference which makes a difference," and you can use this formula as a test for determining which details truly belong in this section. If, for example, providing a plot summary or details about production costs and box-office revenues will make a difference with respect to your thesis (i.e. if a reader needs to know these things in order to process your argument), then this is clearly relevant and belongs in this section; on the other hand, if it doesn't make a difference to your argument, then it probably doesn't belong here. This section should usually be no more than 2-3 paragraphs long.

3. **An in-depth analysis** of the film(s) or other media object(s) under consideration. Your analysis should be interpretive and argumentative in nature. In other words, it is not enough simply to describe what you see on screen; you need also to persuade the reader that this is important, and that it has certain implications that may not be obvious at first glance. (If something is overly obvious, then it's probably not very informative and certainly not worth arguing.) You are not just describing things but providing a "reading" of them. Keep in mind that the analysis you provide in this section constitutes the main support for your thesis statement. Your analysis is the argumentation that you offer to back up your thesis, while the thesis statement should be seen as the logical conclusion of your argument/analysis. In other words, while you have already told the reader what your thesis statement is (in the introduction), it is through your analysis that you must now prove that your thesis is correct or plausible. Ideally, after reading the analysis in this section, the reader should see your thesis statement as the logical outcome. Keeping this in mind as the test of success, you again need to ensure that your analysis is relevant and informative with respect to your thesis statement (if it doesn't make a difference with regard to your thesis, then it can hardly prove it). In addition, you need to make sure that your analysis/argument proves your thesis sufficiently. This is a question of the scope of your thesis, and of your ability to prove it through your interpretive analysis. Have you claimed too much in your thesis? Not enough? Ideally, there should be a perfect match between what you claim in your thesis and what your analysis actually demonstrates. When writing this section, you may find that you have to adjust your thesis (and re-write your introduction accordingly) or look for stronger arguments to support it. This should be the longest section of your paper.

4. **A brief conclusion.** Try not to be too mechanical in summarizing and repeating what you've written, but do make sure that the conclusion demonstrates the paper's overall relevance and coherence. For example, you might return to a detail mentioned in the introduction and use it to highlight the significance of your argument: maybe the detail seemed rather unimportant before but has a very different meaning in the light of your analysis or interpretation. Foregrounding the transformative effect of your argument (i.e. the fact that it makes us see things differently) is a good way to demonstrate the overall importance of your paper, and the device of returning in the end to something mentioned at the beginning is an effective way of giving your paper closure. Obviously, though, it is not the only way to approach the conclusion. You might also demonstrate the relevance of your argument by opening up the scope even farther and considering the questions that your thesis raises for other areas of inquiry. Does your analysis suggest alternative readings for other films or media objects? Does it suggest the need to re-think various assumptions about cinema, about a given genre, or about some other aspect of media inquiry? However you decide to approach it, the point of the conclusion, generally speaking, is to take a step back from arguing for your thesis (you are supposed to be finished doing that by now) and to reflect, on a quasi meta-level, about the overall significance of your argument/thesis. This section should normally be one paragraph in length.

5. **A full list of works cited,** according to MLA (or other established) style.

In addition to the above guidelines, please consult the Duke Writing Studio's handout "Visual Rhetoric/Visual Literacy: Writing About Film" (https://twp.duke.edu/uploads/assets/film.pdf) when conceiving and writing your paper. The handout includes links to several other helpful resources, including similar handouts from Dartmouth and Yale. A more comprehensive guide is provided by Timothy Corrigan, *A Short Guide to Writing about Film*. Eighth Edition (Boston: Pearson, 2011).

### Option #2 – Videographic Work

If you choose instead to produce a videographic assignment (or related type of critical media project), you should similarly submit a 1-2 page proposal in class on **February 26, 2019** (or earlier); you should also be prepared to screen an excerpt or rough cut of your project on the final day of class **(March 12, 2019)**. Videographic work can be either argumentative or more experimental in nature, but you should justify in your proposal why your particular approach is suited both to your subject matter and to your own body of work and development as a scholar and/or practitioner. (A more experimental approach may seem to make more sense for students of art practice than for students of art history/film and media studies, but this is not necessarily true; I would like for you to explain briefly why your approach makes sense for you, in relation to your previous work, future projects, and larger academic or artistic interests.) You should also state the estimated length of your video piece and provide a brief rationale. The final project, which is to consist of your video work and a short (approx. 2-3 pages, in most cases) textual accompaniment, will be due on **Friday, March 22, 2019 (no later than 6:30pm)**.

There are many possible types and modes of videographic work that you might choose to pursue. We will watch a number of examples in class, while the quarterly peer-reviewed journal *[in]Transition* (http://mediacommons.futureofthebook.org/intransition/) might be consulted for a broader overview of existing work.

Video essays need not (and probably should not) be structured like an academic term paper, but they should certainly provide evidence of scholarly research and the conventions pertaining to it. In this respect, it is worth thinking through the guidelines for term papers, above, and considering how and in what respects they either do or do not apply to videographic criticism and analysis, which in terms of content and methodology might follow more traditional principles of humanities-based film studies or instead avail itself of the tools and techniques of digital humanities.

More "experimental" approaches must also demonstrate a high level of practical and critical rigor. They should be executed in such a way as to illuminate or invite speculation about significant aspects of the work or works to which they respond – or the material, semiotic, or other central characteristics of post-cinematic media more generally. They may take the form of short videos, or they may employ other (computational or analog) means for generating images that perform such work.

In all, the emerging field of videographic (and related) studies of moving-image image remains highly experimental and open to innovation. It will thus be one of our central tasks in this course to work through ideas about goals and methods, and more generally about the relations of videographic work to traditional film studies scholarship and to critically informed creative responses.

## Students with Documented Disabilities

Students who may need an academic accommodation based on the impact of a disability must initiate the request with the Office of Accessible Education (OAE). Professional staff will evaluate the request with required documentation, recommend reasonable accommodations, and prepare an Accommodation Letter for faculty dated in the current quarter in which the request is being made. Students should contact the OAE as soon as possible since timely notice is needed to coordinate accommodations. The OAE is located at 563 Salvatierra Walk (phone: 723-1066, URL: http://oae.stanford.edu).

## Course Schedule

### 01.08. Introduction: Parameters for Post-Cinema I

**TEXTS:** Shane Denson and Julia Leyda, "Perspectives on Post-Cinema: An Introduction"; Lev Manovich, "What is Digital Cinema?"; David Bordwell, "Intensified Continuity: Visual Style in Contemporary American Film"; Steven Shaviro, "Post-Continuity: An Introduction"

**VIDEO ESSAYS:** Matthias Stork, "Chaos Cinema"; Kevin L. Ferguson, "Volumetric Cinema"; Selected other video essays. (In-class video screenings)

[Suggestions for further study: David Rodowick, *The Virtual Life of Film*. / André Bazin, "The Ontology of the Photographic Image." / David Bordwell, "Intensified Continuity Revisited." / Michael Allen, "The Impact of Digital Technologies on Film Aesthetics." / W. J. T. Mitchell, "Realism and the Digital Image." / Lev Manovich, *The Language of New Media*. / Shane Denson, "Discorrelated Images: Chaos Cinema, Post-Cinematic Affect, and Speculative Realism."]

### 01.10. Screening: *Transformers* (Michael Bay, 2007)

### 01.15. Parameters for Post-Cinema II

**TEXTS:** John Belton, "If Film is Dead, What is Cinema?"; Miriam de Rosa and Vinzenz Hediger, "Post-What? Post-When? A Conversation on the 'Posts' of Post-Media and Post-Cinema"; Shane Denson, "Speculation, Transition, and the Passing of Post-Cinema"; Ted Nanicelli and Malcolm Turvey, "Against Post-Cinema"

[Suggestions for further study: Rombes, Nicholas. *Cinema in the Digital Age*. / Richard Grusin, "DVDs, Video Games, and the Cinema of Interactions" / Anne Friedberg, "The End of Cinema: Multimedia and Technological Change." / W. J. T. Mitchell, "Realism and the Digital Image." / Friedrich Kittler, "Computer Graphics: A Semi-Technical Introduction." / FILMS: *Transformers: Revenge of the Fallen* (Michael Bay, 2009) / *Transformers: Dark of the Moon* (Michael Bay, 2011) / *Domino* (Tony Scott, 2005) / *Déjà Vu* (Tony Scott, 2006) / *The Taking of Pelham 123* (2009)]

### 01.17. Screening: *Upstream Color* (Shane Carruth, 2013)

### 01.22. Experiences of Post-Cinema I

**TEXTS:** Vivian Sobchack, "The Scene of the Screen: Envisioning Photographic, Cinematic, and Electronic 'Presence'"; Steven Shaviro, "Post-Cinematic Affect"; Shane Denson, "Crazy Cameras, Discorrelated Images, and the Post-Perceptual Mediation of Post-Cinematic Affect"

[Suggestions for further study: Vivian Sobchack, *The Address of the Eye*. / Steven Shaviro, *Post-Cinematic Affect*. / Steven Shaviro, *The Cinematic Body*. / Mark B. N. Hansen, *Bodies in Code*. / Margit Grieb, "Run Lara Run." / Thomas Elsaesser and Malte Hagener, *Film Theory: An Introduction through the Senses*. / Warren Buckland, ed., *Puzzle Films: Complex Storytelling in Contemporary Cinema*. / FILMS: *Mulholland Drive* (David Lynch, 2001) / *Memento* (Christopher Nolan, 2000) / *Batman Begins* (Christopher Nolan, 2005) / *The Dark Knight Rises* (Christopher Nolan, 2008) / *The Dark Knight* (Christopher Nolan, 2012) / *Inception* (Christopher Nolan, 2010) / *Being John Malkovich* (Spike Jonez, 1999) / *Cloud Atlas* (The Wachowskis and Tom Tykwer)]

### 01.24. Screening: *Unfriended* (Leo Gabriadze, 2014)

### 01.29. Experiences of Post-Cinema II

**TEXTS:** Sergi Sánchez, "Towards a Non-Time Image: Notes on Deleuze in the Digital Era"; David Rambo, "The Error-Image: On the Technics of Memory"; Shane Denson, "The Horror of Discorrelation: Mediating Unease in Post-Cinematic Screens and Networks"

[Suggestions for further study: Gilles Deleuze, *Cinema 1*. / Gilles Deleuze, *Cinema 2*. / Patricia Pisters, "Flash-Forward: The Future is Now" / D. N. Rodowick, *Gilles Deleuze's Time Machine*. / Maurizio Lazzarato, "Machines to Crystallize Time." / Mark B. N. Hansen, *New Philosophy for New Media*. / Caleb Crain, "The Thoreau Poison." / Damon Wise, "Shane Carruth Interview: Upstream Color." / Mark B. N. Hansen, "Ubiquitous Sensation" / Shane Denson, Therese Grisham, and Julia Leyda, "Post-Cinematic Affect: Post-Continuity, the Irrational Camera, Thoughts on 3D." / FILMS: *Primer* (Shane Carruth, 2004) / *Looper* (Rian Johnson, 2012) / *Unfriended: The Dark Web* (Stephen Susco, 2018) / *Searching* (Aneesh Chaganty, 2018)]

### 01.31. Screening: *Coraline* (Henry Selick, 2009)

### 02.05. Techniques and Technologies of Post-Cinema

**TEXTS:** Leon Gurevitch, "Cinema Designed: Visual Effects Software and the Emergence of the Engineered Spectacle"; Andreas Sudmann, "Bullet Time and the Mediation of Post-Cinematic Temporality"; Caetlin Benson-Allott, "The Chora Line: RealD Incorporated"; Steven Shaviro, "Splitting the Atom: Post-Cinematic Articulations of Sound and Vision"

[Suggestions for further study: J. P. Telotte, "The Pixar Reality: Digital Space and Beyond" (Chapter 9 in *Animating Space: From Mickey to WALL-E*). / J. P. Telotte, "Digital Effects Animation and the New Hybrid Cinema" (Chapter 10 in *Animating Space*). / Alan Ackerman, "The Spirit of Toys: Resurrection and Redemption in *Toy Story* and *Toy Story 2*." / Livia Monnet, "A-Life and the Uncanny in *Final Fantasy: The Spirits Within*." / Patricia Pisters, *The Neuro-Image: A Deleuzian Filmphilosophy of Digital Screen Culture*. / Henry Jenkins, "Searching for the Origami Unicorn: *The Matrix* and Transmedia Storytelling." (Chapter 3 of *Convergence Culture*). / Wanda Strauven, ed., *The Cinema of Attractions Reloaded*. / Shane Denson and Andreas Jahn-Sudmann, "Digital Seriality: On the Serial Aesthetics and Practices of Digital Games." Steven Shaviro, "Corporate Cannibal" (Chapter 2 in *Post-Cinematic Affect*) / FILMS: *WALL-E* (Andrew Stanton, 2008) / *Final Fantasy: The Spirits Within* (Hironobu Sakaguchi and Motonori Sakakibara, 2001) / *Toy Story* (John Lasseter, 1995) / *Toy Story 2* (John Lasseter, 1999) / *Toy Story 3* (Lee Unkrich, 2010) / *The Matrix Reloaded* (The Wachowskis, 2003) / *Matrix Revolutions* (The Wachowskis, 2003) / *The Animatrix* (Peter Chung, Andrew R. Jones, Yoshiaki Kawajiri, Takeshi Koike, Mahiro Maeda, Kôji Morimoto, Shinichirô Watanabe, 2003) / GAMES: *Enter the Matrix* (Atari, 2003) / *The Matrix Online* (Sega/Warner Bros., 2005) / *Max Payne* (Rockstar Games, 2001) / *Max Payne 2: The Fall of Max Payne* (Rockstar Games, 2003) / *Max Payne 3* (Rockstar Games, 2012)]

### 02.07. Screening: *Paranormal Activity* (Oren Peli, 2007)

### 02.12. Politics of Post-Cinema I

**TEXTS:** Julia Leyda, "Demon Debt: *Paranormal Activity* as Recessionary Post-Cinematic Allegory"; Felix Brinker, "On the Political Economy of the Contemporary (Superhero) Blockbuster Series"; Hito Steyerl, "In Defense of the Poor Image"

[Suggestions for further study: Hito Steyerl, *The Wretched of the Screen*. / Fredric Jameson, *Postmodernism, Or, The Cultural Logic of Late Capitalism*. / Mark B. N. Hansen, "New Media." / Therese Grisham, Julia Leyda, Nicholas Rombes, and Steven Shaviro, "Roundtable Discussion on the Post-Cinematic in *Paranormal Activity* and *Paranormal Activity 2*." / Caetlin Benson-Allott, *Killer Tapes and Shattered Screens* / Kevin J. Wetmore, Jr., *Post-9/11 Horror in American Cinema*. / FILMS: *The Blair Witch Project* (Eduardo Sánchez and Daniel Myrick, 1999) / *Paranormal Activity 2* (Tod Williams, 2010) / *Paranormal Activity 3* (Henry Joost and Ariel Schulman, 2011) / *Paranormal Activity 4* (Henry Joost and Ariel Schulman, 2012) / *Quarantine* (John Erick Dowdle, 2008) / *Cloverfield* (Matt Reeves, 2008) / *Hostel* (Eli Roth, 2005) and sequels / *Saw* (James Wan, 2004) and sequels / *Scary Movie* (Keenen Ivory Wayans, 2000) and sequels / The Marvel Cinematic Universe films and television shows]

### 02.14. Screening: *Gravity* (Alfonso Cuarón, 2013)

### 02.19. Politics of Post-Cinema II

**TEXTS:** Bruce Isaacs, "Reality Effects: The Ideology of the Long Take in the Cinema of Alfonso Cuarón"; Steen Christiansen, "Metamorphosis and Modulation: Darren Aronofsky's *Black Swan*; Elena del Río, "Biopolitical Violence and Affective Force: Michael Haneke's *Code Unknown*"

[Suggestions for further study: Manuel Castells, *The Rise of the Network Society*. / Yann Moulier Boutang, *Cognitive Capitalism*. / Maurizio Lazzarato, "Immaterial Labor." / Alexander Galloway, *The Interface Effect*. / David Golumbia, "High-Frequency Trading: Networks of Wealth and the Concentration of Power." / Matteo Pasquinelli, "Google's PageRank Algorithm: A Diagram of Cognitive Capitalism and the Rentier of the Common Intellect." / FILMS: *Y Tu Mamá Tambien* (Alfonso Caurón, 2001) / *Harry Potter and the Prisoner of Azkaban* (Alfonso Caurón, 2004) / *Children of Men* (Alfonso Caurón, 2006) / *Gravity* (Alfonso Caurón, 2013) / *Funny Games* (Michael Haneke, 1997) / *Code Unknown* (Michael Haneke, 2000) / *Caché* (Michael Haneke, 2005) / *Funny Games* (Michael Haneke, 1997)]

### 02.21. Screening: *Hugo* (Martin Scorsese, 2011)

### 02.26. Archaeologies of Post-Cinema I (Paper/Project Proposals Due!)

**TEXTS:** Francesco Casetti, "The Relocation of Cinema"; Ruth Mayer, "Early/Post-Cinema: The Short Form, 1900/2000"; Richard Grusin, "Post-Cinematic Atavism"; Michael Loren Siegel, "Ride into the Danger Zone: *Top Gun* (1986) and the Emergence of the Post-Cinematic"; Alessandra Raengo, "Life in Those Shadows! Kara Walker's Post-Cinematic Silhouettes"

[Suggestions for further study: Erkki Huhtamo and Jussi Parikka, eds., *Media Archaeology: Approaches, Applications, and Implications*. / Jussi Parikka, *What is Media Archaeology?* / Friedrich Kittler, *Gramophone, Film, Typewriter*. / Jay David Bolter and Richard Grusin, *Remediation*. / Walter Benjamin, "The Work of Art in the Age of Technical Reproduction." / FILMS: *The Artist* (Michel Hazanavicius, 2011) / *Midnight in Paris* (Woody Allen, 2011) / *The Tree of Life* (Terrence Malick, 2011) / *War Horse* (Steven Spielberg, 2011) / *The Help* (Tate Taylor, 2011)]

### 02.28. Screening: *Speed Racer* (The Wachowskis, 2008)

### 03.05. Archaeologies of Post-Cinema II

**TEXTS:** Wolfgang Ernst, "Time-Critical Media Processes" and "A Close Reading of the Electronic 'Time Image'" (both in *Chronopoetics*); Mark B. N. Hansen, "Algorithmic Sensibility: Reflections on the Post-Perceptual Image"

[Suggestions for further study: Friedrich Kittler, *Gramophone, Film, Typewriter* / Wolfgang Ernst, *Chronopoetics* / Bernard Siegert, *Cultural Techniques*]

### 03.07. Screening: *Snowpiercer* (Bong Joon Ho, 2013)

### 03.12. Ecologies of Post-Cinema

**TEXTS:** Adrian Ivakhiv, "The Art of Morphogenesis: Cinema in and beyond the Capitalocene"; Selmin Kara, "Anthropocenema: Cinema in the Age of Mass Extinctions"; Shane Denson, "Post-Cinema After Extinction"

[Suggestions for further study: Steven Shaviro, "Melancholia or, the Romantic Anti-Sublime." / Stephen Rust, Salma Monani, and Sean Cubitt, eds. *Ecocinema Theory and Practice*. / Adrian Ivakhiv, *Ecologies of the Moving Image: Cinema, Affect, Nature*. / Jussi Parikka, *A Geology of Media*. / Shane Denson, "Post-Cinema After Extinction" (blog post) / Shane Denson, "The Glitch as Propaedeutic to a Materialist Theory of Post-Cinema" (blog post) / FILMS: *Melancholia* (Lars von Trier, 2011) / *Avatar* (James Cameron, 2009) / *The Tree of Life* (Terrence Malick, 2011) / *WALL-E* (Andrew Stanton, 2008) / *The Cave of Forgotten Dreams* (Werner Herzog, 2010) / *Fast Food Nation* (Richard Linklater, 2006) / *Darwin's Nightmare* (Hubert Saupert, 2004) / *The Cove* (Louie Psihoyos, 2009) / *An Inconvenient Truth* (Davis Guggenheim, 2006) / *Lossless #3* (Rebecca Baron, Douglas Goodwin, 2008) / *V/H/S* (Matt Bettinelli-Olpin, David Bruckner, Tyler Gillett, Justin Martinez, Glenn McQuaid, Radio Silence, Joe Swanberg, Chad Villella, Ti West, Adam Wingard, 2012) / *V/H/S 2* (Simon Barrett, Jason Eisner, Gareth Evans, Gregg Hale, Eduardo Sánchez, Timo Tjahjanto, Adam Wingard, 2013) / Works by media artist Grégory Chatonsky]

---

### 03.22. Final Projects Due! (by 6:30pm)

## Bibliography

Aarseth, Espen. *Cybertext: Perspectives on Ergodic Literature*. Baltimore: Johns Hopkins UP, 1997.

Ackerman, Alan. "The Spirit of Toys: Resurrection and Redemption in *Toy Story* and *Toy Story 2*." *University of Toronto Quarterly* 74.4 (2005): 895-912.

Allen, Michael. "The Impact of Digital Technologies on Film Aesthetics." *Film Theory and Criticism*. 7th ed. Eds. Leo Braudy and Marshall Cohen. Oxford: Oxford UP, 2008. 824-833.

Bazin, André. "The Ontology of the Photographic Image." Trans. Hugh Gray. *Film Quarterly* 13.4 (Summer, 1960): 4-9.

Belton, John. "If Film is Dead, What is Cinema?" *Screen* 55.4 (2014): 460-470.

Benjamin, Walter. "The Work of Art in the Age of Technical Reproduction." Trans. Harry Zohn. *Illuminations*. Ed. Hannah Arendt. New York: Schocken, 1968. 217-251.

_____. *The Work of Art in the Age of its Technological Reproducibility and Other Writings on Media*. Eds. Michael W. Jennings, Brigid Doherty, and Thomas Y. Levin. Cambridge, MA: Harvard UP, 2008.

Benson-Allott, Caetlin. *Killer Tapes and Shattered Screens: Video Spectatorship from VHS to File Sharing*. Berkeley: U of California P, 2013.

Birchall, Clare, Gary Hall, and Peter Woodbridge. "Deleuze's Postscript on the Societies of Control." Video essay: http://www.youtube.com/watch?v=GIus7lm_ZK0.

Boltanski, Luc, and Eve Chiapello. *The New Spirit of Capitalism*. Trans. Gregory Elliott. New York: Verso, 2007.

Bolter, Jay David, and Richard Grusin. *Remediation*. Cambridge, MA: MIT Press, 2000.

Bordwell, David. "Intensified Continuity: Visual Style in Contemporary American Film." *Film Quarterly* 55.3 (2002): 16-28.

_____. "Intensified Continuity Revisited." *Observations on Film Art*. Blog post, May 27, 2007: http://www.davidbordwell.net/blog/2007/05/27/intensified-continuity-revisited/.

Bordwell, David, Janet Staiger, and Kristin Thompson. *Classical Hollywood Cinema*. New York: Columbia UP, 1985.

Braudy, Leo, and Marshall Cohen, eds. *Film Theory and Criticism*. 7th ed. Oxford: Oxford UP, 2008.

Buckland, Warren, ed. *Puzzle Films: Complex Storytelling in Contemporary Cinema*. Malden: Blackwell, 2009.

Cascio, Jamais. "The Rise of the Participatory Panopticon." *Worldchanging* (blog). May 4, 2005: http://www.worldchanging.com/archives/002651.html.

Casetti, Francesco. "The Relocation of Cinema." *NECSUS: European Journal of Media Studies* 2 (2012): http://www.necsus-ejms.org/the-relocation-of-cinema/. Rpt. in Denson and Leyda, eds. *Post-Cinema*.

Castells, Manuel. *The Rise of the Network Society*. 2nd ed. Vol. 1: *The Information Age: Economy, Society, and Culture*. Cambridge: Blackwell, 2000.

Chun, Wendy Hui Kyong, and Thomas Keenan, eds. *New Media, Old Media: A History and Theory Reader*. New York: Routledge, 2006.

Crain, Caleb. "The Thoreau Poison." *The New Yorker*. May 8, 2013. http://www.newyorker.com/books/page-turner/the-thoreau-poison.

Corrigan, Timothy. *A Short Guide to Writing about Film*. 8th ed. London: Pearson, 2012.

Corrigan, Timothy, and Patricia White. *The Film Experience: An Introduction*. 3rd ed. Boston: Bedford/St. Martin's, 2012.

De Rosa, Miriam, and Vinzenz Hediger. "Post-What? Post-When? A Conversation on the 'Posts' of Post-Media and Post-Cinema." *Cinéma et Cie* 16.26-27 (2016): 9-20.

Deleuze, Gilles. *Cinema 1: The Movement-Image*. Trans. Hugh Tomlinson and Barbara Habberjam. Minneapolis: U of Minnesota P, 1986.

_____. *Cinema 2: The Time-Image*. Trans. Hugh Tomlinson and Robert Galeta. Minneapolis: U of Minnesota P, 1989.

_____. "Postscript on the Societies of Control." *October* 59 (1992): 3-7.

Denson, Shane. "Crazy Cameras, Discorrelated Images, and the Post-Perceptual Mediation of Post-Cinematic Affect." In Denson and Leyda, eds. *Post-Cinema*.

_____. "Discorrelated Images: Chaos Cinema, Post-Cinematic Affect, and Speculative Realism." Talk delivered as part of the Initiative for Interdisciplinary Media Research's film series "Chaos Cinema?" at the Leibniz University of Hannover. June 21, 2012, Hannover. Online: http://wp.me/p1xJM8-hs.

_____. "The Glitch as Propaedeutic to a Materialist Theory of Post-Cinematic Affect." Blog Post: http://wp.me/p1xJM8-Es.

_____. "The Horror of Discorrelation: Mediating Unease in Post-Cinematic Screens and Networks." *Journal of Cinema and Media Studies*, forthcoming.

_____. "Post-Cinema After Extinction." *Media Fields* 13 (2018). Online: http://mediafieldsjournal.org/post-cinema-after-extinction/.

_____. "Speculation, Transition, and the Passing of Post-Cinema." *Cinéma et Cie* 16.26-27 (2016): 21-32.

_____. "WALL-E vs. Chaos (Cinema)." Talk delivered as part of the Initiative for Interdisciplinary Media Research's film series "Chaos Cinema?" at the Leibniz University of Hannover. July 19, 2012, Hannover. Online: http://wp.me/p1xJM8-iD.

Denson, Shane, and Andreas Jahn-Sudmann. "Digital Seriality: On the Serial Aesthetics and Practices of Digital Games." *Eludamos: Journal for Computer Game Culture* 7.1 (2013): 1-32. http://www.eludamos.org/index.php/eludamos/article/view/vol7no1-1/7-1-1-pdf.

Denson, Shane, and Julia Leyda, eds. *Post-Cinema: Theorizing 21st-Century Film*. Sussex: REFRAME Books, 2015.

Denson, Shane, Therese Grisham, and Julia Leyda. "Post-Cinematic Affect: Post-Continuity, the Irrational Camera, Thoughts on 3D." *La Furia Umana* 14 (2012): http://bit.ly/T3Q5rs. Also available here: http://www.academia.edu/1993403/_Post-Cinematic_Affect_PostContinuity_the_Irrational_Camera_Thoughts_on_3D_. Rpt. in Denson and Leyda, eds. *Post-Cinema*.

Elsaesser, Thomas. "Early Film History and Multimedia: An Archaeology of Possible Futures?" *New Media, Old Media: A History and Theory Reader*. Eds. Wendy Hui Kyong Chun and Thomas Keenan. New York: Routledge, 2006. 13-25.

Elsaesser, Thomas, and Malte Hagener. *Film Theory: An Introduction through the Senses*. New York: Routledge, 2010.

Ernst, Wolfgang. *Chronopoetics: The Temporal Being and Operativity of Technological Media*. New York: Rowman & Littlefield, 2016.

Ferguson, Thomas L. "Volumetric Cinema." *[in]Transition: Journal of Videographic Film & Moving Image Studies* 2.1 (2015): http://mediacommons.futureofthebook.org/intransition/2015/03/10/volumetric-cinema.

Fisher, Mark. *Capitalist Realism*. London: Zero Books, 2009.

Foucault, Michel. *Discipline and Punish: The Birth of the Prison*. New York: Vintage, 1995.

Friedberg, Anne. "The End of Cinema: Multimedia and Technological Change." *Reinventing Film Studies*. Ed. Christine Gledhill and Linda Williams. London: Arnold, 2000. 438–452.

Galloway, Alexander. *Gaming: Essays on Algorithmic Culture*. Minneapolis: U of Minnesota P, 2006.

_____. *The Interface Effect*. Cambridge: Polity, 2012.

Golumbia, David. "High-Frequency Trading: Networks of Wealth and the Concentration of Power." *Social Semiotics* 23.2 (2013): 278-299. Pre-print: http://www.uncomputing.org/wp-content/uploads/2012/12/golumbia.high-frequency-trading.pre-pressDec2012.pdf.

Grieb, Margit. "Run Lara Run." *ScreenPlay: Cinema/Videogames/Interfaces*. Eds. Geoff King and Tanya Krzywinska. London: Wallflower, 2002. 157-170.

Grisham, Therese, Julia Leyda, Nicholas Rombes, and Steven Shaviro. "Roundtable Discussion on the Post-Cinematic in *Paranormal Activity* and *Paranormal Activity 2*." *La Furia Umana* 10 (2011): http://www.lafuriaumana.it/index.php?option=com_content&view=article&id=385:roundtable-discussion-about-post-cinematic&catid%20=59:la-furia-umana-nd-10-autumn-2011&Itemid=61. Also available here: http://www.academia.edu/966735/Roundtable_Discussion_about_the_PostCinematic_in_Paranormal_Activity_and_Paranormal_Activity_2. Rpt. in Denson and Leyda, eds. *Post-Cinema*.

Grusin, Richard. "DVDs, Video Games, and the Cinema of Interactions." *Multimedia Histories: From the Magic Lantern to the Internet*. Eds. James Lyons and John Plunkett. Exeter: U of Exeter P, 2007. 209-221. Rpt. in Denson and Leyda, eds. *Post-Cinema*.

Gurevitch, Leon. "Cinema Designed: Visual Effects Software and the Emergence of the Engineered Spectacle." In Denson and Leyda, eds. *Post-Cinema*.

Hansen, Mark B.N. "Algorithmic Sensibility: Reflections on the Post-Perceptual Image." In Denson and Leyda, eds. *Post-Cinema*.

_____. *Bodies in Code: Interfaces with Digital Media*. New York: Routledge, 2006.

_____. "Living (with) Technical Time: From Media Surrogacy to Distributed Cognition." *Theory, Culture & Society* 26 (2-3): 294-315.

_____. "Media Theory." *Theory, Culture & Society* 23 (2-3): 297-306.

_____. "New Media." *Critical Terms for Media Studies*. Eds. W.J.T. Mitchell and Mark B.N. Hansen. Chicago and London: U of Chicago P, 2010. 172-185.

_____. *New Philosophy for New Media*. Cambridge, MA: MIT, 2004.

_____. "Ubiquitous Sensation: Toward an Atmospheric, Collective, and Microtemporal Model of Media." *Throughout: Art and Culture Emerging with Ubiquitous Computing*. Ed. Ulrik Ekman. Cambridge: MIT, 2013. 63-88.

Hoberman, J. *Film after Film: Or, What Became of 21st Century Film?* London: Verso, 2012.

Huhtamo, Erkki, and Jussi Parikka, eds., *Media Archaeology: Approaches, Applications, and Implications*. Berkeley: U of California P, 2011.

Ivakhiv, Adrian. "The Art of Morphogenesis: Cinema in and beyond the Capitalocene." In Denson and Leyda, eds. *Post-Cinema*.

_____. *Ecologies of the Moving Image: Cinema, Affect, Nature*. Waterloo: Wilfrid Laurier UP, 2013.

Jameson, Fredric. *Postmodernism, Or, The Cultural Logic of Late Capitalism*. Durham: Duke UP, 1991.

Jenkins, Henry. *Convergence Culture: Where Old and New Media Collide*. New York and London: New York UP, 2006.

Kara, Selmin. "Anthropocenema: Cinema in the Age of Mass Extinctions." In Denson and Leyda, eds. *Post-Cinema*.

Kittler, Friedrich. "Computer Graphics: A Semi-Technical Introduction." *Grey Room* 2 (2001): 30-45.

_____. *Gramophone, Film, Typewriter*. Stanford: Stanford UP, 1999.

Krapp, Peter. *Noise Channels: Glitch and Error in Digital Culture*. Minneapolis: U of Minesota P, 2011.

Lazzarato, Maurizio. "Immaterial Labor." *Radical Thought in Italy: A Potential Politics*. Eds. Paolo Virno and Michael Hardt. Minneapolis: U of Minnesota P, 1996. 133-147.

_____. "Machines to Crystalize Time: Bergson." *Theory, Culture & Society* 24.6 (2007): 93-122.

Leyda, Julia. "Demon Debt: *Paranormal Activity* as Recessionary Post-Cinematic Allegory." *Jump Cut: A Review of Contemporary Media* 56 (2014-15): http://www.ejumpcut.org/currentissue/LeydaParanormalActivity/. Rpt. in Denson and Leyda, eds. *Post-Cinema*.

Manovich, Lev. *The Language of New Media*. Cambridge, MA: MIT Press, 2001.

_____. "What is Digital Cinema?" Online at the author's website: http://www.manovich.net/TEXT/digital-cinema.html.

Marshall, P., ed. *The Celebrity Culture Reader*. New York: Routledge, 2006.

Massumi, Brian. *Parables for the Virtual: Movement, Affect, Sensation*. Durham: Duke UP, 2002.

McLuhan, Marshall. *Understanding Media: The Extensions of Man*. London and New York: Routledge, 1964.

Mitchell, W. J. T. "Realism and the Digital Image." *Critical Realism in Contemporary Art*. Eds. Hilde van Gelder & Jan Baetens. Leuven: Leuven UP. 13-27.

Mitchell, W.J.T., and Mark B.N. Hansen, eds. *Critical Terms for Media Studies*. Chicago and London: U of Chicago P, 2010.

Monnet, Livia. "A-Life and the Uncanny in *Final Fantasy: The Spirits Within*." *Science Fiction Studies* 31.1 (2004): 97-121.

Moulier Boutang, Yann. *Cognitive Capitalism*. Cambridge: Polity, 2011.

Nanicelli, Ted, and Malcolm Turvey. "Against Post-Cinema." *Cinéma et Cie* 16.26-27 (2016): 33-43.

Nunes, Mark, ed. *Error: Glitch, Noise, and Jam in New Media Cultures*. New York: Bloomsbury, 2011.

Palmer, Lorrie. "Cranked Masculinity: Hypermediation in Digital Action Cinema." *Cinema Journal* 51.4 (2012): 1-25.

Parikka, Jussi. *A Geology of Media*. Minneapolis: U of Minnesota P, 2015.

_____. *What is Media Archaeology?* Cambridge: Polity, 2012.

Pasquinelli, Matteo. "Google's PageRank Algorithm: A Diagram of Cognitive Capitalism and the Rentier of the Common Intellect." *Deep Search: The Politics of Search Beyond Google*. Eds. Konrad Becker and Felix Stalder. Innsbruck: Studienverlag, 2009. 152-162. Author's repository: http://matteopasquinelli.com/docs/Pasquinelli_PageRank.pdf.

Pisters, Patricia. "Flash-Forward: The Future is Now." In Denson and Leyda, eds. *Post-Cinema*.

_____. *The Neuro-Image: A Deleuzian Filmphilosophy of Digital Screen Culture*. Stanford: Stanford UP, 2012.

Prince, Stephen. "True Lies: Perceptual Realism, Digital Images, and Film Theory." *Film Quarterly* 49.3: 27-37.

Rambo, David. "The Error-Image: On the Technics of Memory." In Denson and Leyda, eds. *Post-Cinema*.

Rodowick, D. N. *Gilles Deleuze's Time Machine*. Durham: Duke UP, 1997.

_____. *The Virtual Life of Film*. Cambridge: Harvard UP, 2007.

Rombes, Nicholas. *Cinema in the Digital Age*. New York: Wallflower P, 2009.

Rust, Stephen, Salma Monani, and Sean Cubitt, eds. *Ecocinema Theory and Practice*. New York: Routledge, 2012.

Shaviro, Steven. *The Cinematic Body*. Minneapolis: U of Minnesota P, 1993.

_____. *Connected: Or What it Means to Live in the Network Society*. Minneapolis: U of Minnesota P, 2003.

_____. Steven Shaviro, "Melancholia or, the Romantic Anti-Sublime." *Sequence* 1.1 (2012): http://reframe.sussex.ac.uk/sequence1/1-1-melancholia-or-the-romantic-anti-sublime/.

_____. *Post-Cinematic Affect*. Winchester, UK: Zero Books, 2010.

_____. "Post-Cinematic Affect: On Grace Jones, *Boarding Gate* and *Southland Tales*." *Film-Philosophy* 14.1 (2010): 1-102.

Siegert, Bernhard. *Cultural Techniques: Grids, Filters, Doors, and Other Articulations of the Real*. New York: Fordham University Press, 2015.

Sobchack, Vivian. *The Address of the Eye: A Phenomenology of Film Experience*. Princeton: Princeton UP, 1992.

_____. "The Scene of the Screen: Envisioning Photographic, Cinematic, and Electronic 'Presence'." *Carnal Thoughts: Embodiment and Moving Image Culture*. Berkeley and Los Angeles: U of California P, 2004. 135-162.

Steyerl, Hito. *The Wretched of the Screen*. Berlin: Sternberg Press, 2012.

Stork, Matthias. "Chaos Cinema." Video essay in three parts. <http://blogs.indiewire.com/pressplay/matthias-stork-chaos-cinema-part-3#>.

Strauven, Wanda, ed. *The Cinema of Attractions Reloaded*. Amsterdam: Amsterdam UP, 2006.

Sudmann, Andreas. "Bullet Time and the Mediation of Post-Cinematic Temporality." In Denson and Leyda, eds. *Post-Cinema*.

Telotte, J. P. *Animating Space: From Mickey to WALL-E*. Lexington: UP of Kentucky, 2010.

Tofts, Darren. "Truth at Twelve Thousand Frames per Second: *The Matrix* and Time-Image Cinema." *24/7: Time and Temporality in the Network Society*. Eds. Robert Hassan and Ronald E. Purser. Stanford: Stanford UP, 2007. 109-121.

Tryon, Chuck. *Reinventing Cinema: Movies in the Age of Media Convergence*. Piscataway, NJ: Rutgers UP, 2009.

Wark, McKenzie. *Gamer Theory*. Cambridge: Harvard UP, 2007. Version 2.0 available online: http://www.futureofthebook.org/gamertheory2.0/.

Wetmore, Kevin J., Jr. *Post-9/11 Horror in American Cinema*. London: Continuum, 2012.

Wise, Damon. "Shane Carruth Interview: Upstream Color." *Empire Blogs*. January 5, 2014. http://www.empireonline.com/empireblogs/words-from-the-wise/post/p1440.
